version: '3.7'

services:
  web:
    image: "gcr.io/tennisbana1/cloudbuild1"
    command:
      - /bin/sh
      - -c
      - |
        cd backend
        python manage.py migrate 
        python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./:/usr/src/
    ports:
      - 8080:8080
